import type { NextComponentType } from 'next'
import Head from 'next/head'

export const Header: NextComponentType = () => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
